//  danh muc va danh sach
export const GROUP_NUMBER = 'GP01';
export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_FAILED = 'COURSE_FAILED';

export const COURSE_CATEGORY_SUCCESS = 'COURSE_CATEGORY_SUCCESS';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';


export const COURSE_DETAIL_SUCCESS = "COURSE_DETAIL_SUCCESS";
export const COURSE_ADD_TO_CART = "COURSE_ADD_TO_CART";
export const REGISTER_COURSE_REQUEST =
  "REGISTER_COURSE_REQUEST";
export const REGISTER_COURSE_SUCCESS =
  "REGISTER_COURSE_SUCCESS";
export const REGISTER_COURSE_FAILED = "REGISTER_COURSE_FAILED";

export const AUTHSIGNIN_REQUEST = "AUTHSIGNIN_REQUEST";
export const AUTHSIGNIN_SUCCESS = "AUTHSIGNIN_SUCCESS";
export const AUTHSIGNIN_FAILED = "AUTHSIGNIN_FAILED";

export const SIGNUP_REQUEST = "SIGNUPREQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const CANCEL_COURSE_REQUEST = "CANCEL_COURSE_REQUEST";
export const CANCEL_COURSE_SUCCESS = "CANCEL_COURSE_SUCCESS";
export const CANCEL_COURSE_FAILED = "CANCEL_COURSE_FAILED";

export const GET_KEYWORD = "GET_KEYWORD";

//GET USER PAGINATION
export const USERLIST_REQUEST = "USERLIST_REQUEST";
export const USERLIST_SUCCESS = "USERLIST_SUCCESS";
export const USERLIST_FAILED = "USERLIST_FAILED";

//GET USER INFO
export const GETUSERINFO_REQUEST = "GETUSERINFO_REQUEST";
export const GETUSERINFO_SUCCESS = "GETUSERINFO_SUCCESS";
export const GETUSERINFO_FAILED = "GETUSERINFO_FAILED";

//MODAL
export const OPENMODAL = "OPENMODAL";
export const CLOSEMODAL = "CLOSEMODAL";

//SUBMIT
export const ONSUBMIT_REQUEST = "ONSUBMIT_REQUEST";
export const ONSUBMIT_SUCCESS = "ONSUBMIT_SUCCESS";
export const ONSUBMIT_FAILED = "ONSUBMIT_FAILED";
export const GETKEYWORD = "GETKEYWORD";

// show list user
export const USER_SELECTOR_REQUEST = "USER_SELECTOR_REQUEST";
export const USER_SELECTOR_SUCCESS = "USER_SELECTOR_SUCCESS";
export const USER_SELECTOR_FAILED = "USER_SELECTOR_FAILED";

export const USER_WAITING_REQUEST = "USER_WAITING_REQUEST";
export const USER_WAITING_SUCCESS = "USER_WAITING_SUCCESS";
export const USER_WAITING_FAILED = "USER_WAITING_FAILED";


export const USER_JOINED_REQUEST = "USER_JOINED_REQUEST";
export const USER_JOINED_SUCCESS = "USER_JOINED_SUCCESS";
export const USER_JOINED_FAILED = "USER_JOINED_FAILED";


export const GET_CODECOURSE = "GET_CODECOURSE";


export const ADMIN_REGISTER_COURSE_REQUEST = "ADMIN_REGISTER_COURSE_REQUEST";
export const ADMIN_REGISTER_COURSE_SUCCESS = "ADMIN_REGISTER_COURSE_SUCCESS";
export const ADMIN_REGISTER_COURSE_FAILED = "ADMIN_REGISTER_COURSE_FAILED";
